---
abstract: 'Constructor generator'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-Constructor
provides:
  Class::Accessor::Constructor:
    file: lib/Class/Accessor/Constructor.pm
    version: 1.111590
  Class::Accessor::Constructor::Base:
    file: lib/Class/Accessor/Constructor/Base.pm
    version: 1.111590
requires:
  Carp: 0
  Class::Accessor: 0
  Class::Accessor::Complex: 0
  Class::Accessor::Installer: 1.100880
  Data::Inherited: 0
  Tie::Hash: 0
  constant: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Class-Accessor-Constructor
  homepage: http://search.cpan.org/dist/Class-Accessor-Constructor/
  repository: git://github.com/hanekomu/Class-Accessor-Constructor.git
version: 1.111590
